spring:
  application:
    name: MovieInsight
  data:
    mongodb:
      uri: mongodb://localhost:27017/movieInsight
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy  # camelCase → snake_case
      auto-index-creation: true          # Create indexes automatically
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Root@1234

server:
  port: 8080

logging:
  level:
    org.zalando.logbook: TRACE

